package net.studyprojects.financas.modelo;

public enum FormaPagamento {
	CARTAO_DE_CREDITO_DINERS, CARTAO_DE_CREDITO_MASTERCARD,
	CARTAO_DE_CREDITO_VISA, DEBITO_AUTOMATICO_BB, 
	DEBITO_AUTOMATICO_BRADESCO_PRIME, DEBITO_AUTOMATICO_CITIBANK,
	DEBITO_AUTOMATICO_ITAU, DEBITO_BB, DEBITO_BRADESCO_PRIME,
	DEBITO_CITIBANK, DEBITO_ITAU 
}
